apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: security-operator
  template:
    metadata:
      labels:
        name: security-operator
    spec:
      serviceAccountName: security-operator
      containers:
        - name: security-operator
          # Replace this with the built image name
          image: shehani123/example-security1-operator:v0.0.1
          command:
            - security-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "security-operator"